#!/usr/bin/env python3
import sys, re, codecs

emoji_dict = {
  "feat": "\U00002728",
  "sparkles": "\U00002728",
  "remove": "\U0001F525",
  "fire": "\U0001F525",
  "bug": "\U0001F41B",
  "fix": "\U0001F41B",
  "refactor": "\U0000267B",
  "perf": "\U000026A1",
  "hotfix": "\U0001F691",
  "doc": "\U0001F4A1",
  "comment": "\U0001F4A1",
  "deploy": "\U0001F680",
  "rocket": "\U0001F680",
  "ui": "\U0001F484",
  "style": "\U0001F484",
  "version": "\U0001F516",
  "tag": "\U0001F516",
  "warning": "\U0001F6A8",
  "lint": "\U0001F6A8",
  "pod": "\U0001F4E6",
  "depend": "\U0001F4E6",
  "ci": "\U0001F477",
  "logger": "\U0001F4C8",
  "localize": "\U0001F310",
  "typo": "\U0000270F",
  "pencil": "\U0000270F",
  "resource": "\U0001F69A",
  "truck": "\U0001F69A",
  "test": "\U00002705"
}

commit_msg_filepath = sys.argv[1]

regex = re.compile(r"(:([a-zA-Z0-9]+):)((.|\n)*)", re.MULTILINE)

commit_msg = ''
with codecs.open(commit_msg_filepath, 'r', 'utf-8') as fh:
  commit_msg = fh.read()

mt = re.match(regex, commit_msg)
if mt:
  emoji = ''
  emotext = mt.group(2)
  message = mt.group(3)
  if emotext in emoji_dict: 
    emoji = emoji_dict[emotext]
  else:
    print("Incorrect gitmoji message.")
    sys.exit(1)
  with codecs.open(commit_msg_filepath, 'w', 'utf-8') as fh:
    fh.write('%s%s' % (emoji, message))
